export const LOGIN_ENDPOINT = '/Users/login'
export const PARTY_ENDPOINT = '/parties'
export const USER_ENDPOINT = '/Users'
export const DOCUMENT_ENDPOINT = '/documents'
export const FILE_UPLOAD_ENDPOINT = '/containers/embleme/upload'
